#!/bin/bash
. /etc/rc.d/init.d/functions
LOG_BASE="/xwkj/logs/"
APP_BASE="/xwkj/app"
ProjectName="op-bmc-api"
projectName="bmc-api"
pidFile="${LOG_BASE}/${ProjectName}/${projectName}.pid"
cpucount=$(cat /proc/cpuinfo| grep "processor"| wc -l)
listen="0.0.0.0:5000"
#gunic=$(rpm -qa |grep gunicorn)
prog=${ProjectName}
accesslogfile="${LOG_BASE}/${ProjectName}/bmc-api-access.log"
errorlogfile="${LOG_BASE}/${ProjectName}/bmc-api-error.log"

gunic="/usr/local/bin/gunicorn"

if (( $# <= 0 )); then
    echo "./console start 启动服务"
    echo "./console stop 停止服务"
    echo "./console restart 重启服务"
    exit 0
fi

function fnstart() {

    su ops -c "${gunic} -u ops  -w ${cpucount} --access-logfile ${accesslogfile}   --log-level "debug" --error-logfile ${errorlogfile} -p ${pidFile} -b ${listen} -D boot:app"
    retval=$?
    [ $retval -eq 0 ] && action "Starting $prog: " /bin/true ||action "Starting $prog: " /bin/false
    return $retval
}

function fnstop() {
    su ops -c "pkill -f ${pidFile}"
    retval=$?
    [ $retval -eq 0 ] && rm -f ${pidFile} && action "Stopping $prog: " /bin/true||action "Stopping $prog: " /bin/false
    return $retval
}

function fnrestart() {
    fnstop
    sleep 2
    fnstart
}

case $1 in
        start)
            fnstart

    ;;
        stop)
            fnstop
    ;;
        restart)
            fnrestart
    ;;
        install)
            fninstall
    ;;
esac
